FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/admin/package*.json ./
RUN npm install
COPY frontend/admin /app
RUN VITE_BASE_PATH=/admin/ npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.static.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
