{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ .Values.env.maxUploadSizeMb }}m"
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls: {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /admin/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-admin
                port: { number: 80 }
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port: { number: 8000 }
          - path: /v1/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port: { number: 8000 }
          - path: /portal/v1/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port: { number: 8000 }
          - path: /oai
            pathType: Exact
            backend:
              service:
                name: {{ .Release.Name }}-api
                port: { number: 8000 }
          - path: /iiif/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-cantaloupe
                port: { number: 8182 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-portal
                port: { number: 80 }
{{- end }}
